name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t meriem899/react-app:$IMAGE_TAG .
          docker push meriem899/react-app:$IMAGE_TAG

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Forward traffic to Kubernetes API server
        run: |
          ssh -i ~/.ssh/id_rsa -L 6443:10.0.1.240:6443 -f -N ec2-user@54.170.4.216

      - name: Apply Kubernetes deployment
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl set image deployment/react-app react-app=meriem899/react-app:$IMAGE_TAG
          kubectl rollout restart deployment/react-app

      - name: Verify deployment
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl get deployments
