jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start the SSH agent
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
          echo "SSH_AGENT_PID: $SSH_AGENT_PID"

          # Add the private key to the SSH agent
          ssh-add ~/.ssh/id_rsa

      - name: Debug SSH key
        run: |
          ssh-keygen -l -f ~/.ssh/id_rsa

      - name: Forward traffic to Kubernetes API server
        run: |
          ssh -i ~/.ssh/id_rsa -L 6443:10.0.1.240:6443 -f -N ec2-user@54.170.4.216

      - name: Debug kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml config view

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/<your-deployment-name>